### ISSUE TITLE
How do you use this? 

### ISSUE THREAD

**Issue by nifri** [baztian/rfid-squeezectl#1]
I have everything set up. The RFID reader is talking to the raspi, your script is talking to the squeezebox. I swipe an RFID card and the uid is read and used as the playlist name. 

The squeezbox does not find that playlist and stops playing the music that was playing before the swipe. So everything seems to be working except translating the uid to some meaningful playlist name. 

Am I missing something or is the code not finished yet? 

Thanks

**Comment by nifri** [comment]
Ok, I figured it out. Here a tutorial for the newcomers to this project.

1.) Make sure that on the Logitech Media Server the "Playlist folder" is set. If it is not, create a folder where you want to store the playlists and select it in the Logitech Media Server settings. Klick Apply.

![image](https://user-images.githubusercontent.com/32237350/99186822-3d59db80-2753-11eb-8174-3fb58dfddc9f.png)

2.) Start rfid-squeezectl and swipe an RFID tag. The UID will be returned on the console. In the example below the UID of the tag is 108-144-164-22-78.

![ScreenClip](https://user-images.githubusercontent.com/32237350/99186829-4b0f6100-2753-11eb-940d-61ccc5948e27.png)

3.) Now you need to create a playlist with the name of the UID of the tag. The easiest way that I have found is:
3a) Play the songs / audiobooks / radiostation or whatever you want to have in your playlist on the Squeezebox / Logitech Media Server. Add titles to the playlist as you like and arrange them in your preferred order. 
3b) Once you are satisfied with your playlist open a new browser window and enter the following URL into the address bar:
servername:serverport/status.m3u - where servername is the address of your Logitech Media Server, serverport is the port of the Logitech Media Server.
For example: music:9000/status.m3u
3c) Press enter and the status.m3u will be presented for download.

![ScreenClip](https://user-images.githubusercontent.com/32237350/99186838-5498c900-2753-11eb-9376-8a765059af1c.png)

4.) Rename the "status" part of status.m3u to the UID of the tag from step 2. So in this example rename status.m3u to 108-144-164-22-78.m3u.
5.) Store the 108-144-164-22-78.m3u in the "Playlist Folder" from step 1.
6.) Swipe the tag again and the playlist will play.

**Comment by baztian** [comment]
Cool, thanks Nico. I guess initially the missing piece was the nanning of the playlist. It has to be named after the uuid.
